keys: move signing part out of find_by_thp() and to find_jws()
Handle just signing keys in find_jws(), to make sure we are
responding only to proper queries.

Tests were also failing to detect this issue and were updated
accordingly.

Issue discovered by Twitter Kernel and OS team during a source
code audit while evaluating Tang/Clevis for their needs.

Fixes CVE-2021-4076

diff --git a/tests/helpers b/tests/helpers
--- a/tests/helpers
+++ b/tests/helpers
@@ -84,3 +84,8 @@ valid_key_perm() {
     fi
     [ "${_perm}" = "440" ]
 }
+
+expected_fail () {
+    echo "Test was expected to fail" >&2
+    exit 1
+}
